name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.3
  - cuda-toolkit=12.1
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - plyfile
  - tqdm
  - numpy<2.0
  - pillow
  - matplotlib
  - gcc_linux-64=12.4
  - gxx_linux-64=12.4
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
    - ninja
